import { db, Episode, EpisodePeople, EpisodeTags, People } from "astro:db";

// https://astro.build/db/seed
export default async function seed() {
  console.log("Seeding Episodes");
  await db.insert(Episode).values([
    {
      id: 1,
      slug: "s4e50",
      season: 4,
      episode: 50,
      airDate: new Date("2024-05-02"),
      title:
        "Captain Wolf of the SS SALTINES!! Guns of Icarus with the CPlus Community!",
      description:
        "Wolf and Matorin host some Guns of Icarus, captaining steampunk airships against each other! Pretty cool if I do say so myself. Even some rando's joined in!",
      format: "community",
      duration: 7004,
      ytID: "BuPwpXTFabk",
    },
    {
      id: 2,
      slug: "s4e51",
      season: 4,
      episode: 51,
      title: "The Carnival comes to Town, but the clowns have always been here",
      description:
        "The Contacts Plus farm takes on homesteading in another episode, the crew all eagerly awaiting the fair at the end. Everyone brings the best of their gear, then goes fishing and shooting targets for a LOOONG time... longer for Glitch as he displays a bit of a Gambling problem, but also skill as he starts to figure out patterns. All the tickets and all the carnival fun as the clowns of the crew enjoy their time at a fun fair.",
      format: "gameNight",
      airDate: new Date("2024-05-03"),
      duration: 9515,
      ytID: "8g80M9hN4SM",
    },
    {
      id: 3,
      slug: "s4e52",
      season: 4,
      episode: 52,
      title: "Def is Home from Japan!",
      description:
        "After the crew had waited for a month and watched eagerly, DefHammer has returned from a trip to Japan with cool stories, neat photos, and a little surprise in his own journeys of technology. Join us in hearing about cool shrines, yummy foods galore, and an awakening in a Yodobashi in Kyoto.",
      format: "community",
      airDate: new Date("2024-05-04"),
      duration: 7384,
      ytID: "vb2pnYFw6Bo",
    },
    {
      id: 4,
      slug: "s4e53",
      season: 4,
      episode: 54,
      title: "Slimy Grubs, our Arch Nemesis",
      description:
        "We give Hammerwatch a try, as the wolf gets a cold and Wolf himself tries to strategize. Lots of fun in a rogue style game, but the Maggot Queen is our bane. We will need to get more help and strategize better next time.",
      format: "gameNight",
      airDate: new Date("2024-05-10"),
      duration: 11907,
      ytID: "ybrAP322U4Y",
    },
    {
      id: 5,
      slug: "s4e55",
      season: 4,
      episode: 55,
      title: "Wolf is a gummigoo and Noot is a pomni",
      description:
        "Topics include: Wolf is a gummigoo. That's it. That's the whole episode.",
      format: "withWolf",
      airDate: new Date("2024-05-11"),
      duration: 7191,
      ytID: "7J3J6uu_Wps",
    },
    {
      id: 6,
      slug: "s4e56",
      season: 4,
      episode: 56,
      title: "Finally some good updates!",
      description:
        "More Star Citizen with the crew! (and Defhammer) With less bugs, more UI, and more missions!",
      format: "gameNight",
      airDate: new Date("2024-05-17"),
      duration: 13989,
      ytID: "Sw89kpUXG-k",
    },
    {
      id: 7,
      slug: "s4e57",
      season: 4,
      episode: 57,
      title: "MENTAL HEALTH MATTERS",
      description:
        "The broken™ crew tries their hardest to be genuinely serious about mental health, but as usual they get sidetracked by the usual chaos. We're in this together. You're not alone.",
      format: "withWolf",
      airDate: new Date("2024-05-18"),
      duration: 7012,
      ytID: "wrqZELQT8qw",
    },
    {
      id: 8,
      slug: "s4e58",
      season: 4,
      episode: 58,
      title: "Contacts Plus Tavern is BACK OPEN FOR BUSINESS",
      description:
        "The Contacts Plus Tavern RETURNS after a brief hiatus, back with more staff, more chaos, and MORE GRILLED GROGIUM!!",
      format: "community",
      airDate: new Date("2024-05-23"),
      duration: 7825,
      ytID: "-w4eda4DA0k",
    },
    {
      id: 9,
      slug: "s4e59",
      season: 4,
      episode: 59,
      title: "Angery Wolf Seisenbacher Simulator",
      description:
        "You thought you have seen Wolf angry... until now. The Contacts Plus crew plays Hammerwatch!",
      format: "gameNight",
      airDate: new Date("2024-05-24"),
      duration: 20035,
      ytID: "pGgb1X37Qjw",
    },
    {
      id: 10,
      slug: "s4e60",
      season: 4,
      episode: 60,
      title: "Dementia, Pineapple on Pizza, and Headless Lounge Love??",
      description:
        "In this episode, some returning guests and our resident blue wolf play some old and brand new games around the classic 'Whose Line Is It Anyway?' format.",
      format: "whoseLine",
      airDate: new Date("2024-05-25"),
      duration: 7397,
      ytID: "1qqVYa4d9Wg",
    },
  ]);

  console.log("Seeding Episode Tags");
  await db.insert(EpisodeTags).values([
    { id: 1, episodeID: 1, tag: "community night" },
    { id: 2, episodeID: 1, tag: "guns of icarus" },
    { id: 3, episodeID: 1, tag: "gaming" },
    { id: 4, episodeID: 2, tag: "game night" },
    { id: 5, episodeID: 2, tag: "stardew valley" },
    { id: 6, episodeID: 3, tag: "podcast" },
    { id: 7, episodeID: 4, tag: "community night" },
    { id: 8, episodeID: 4, tag: "game night" },
    { id: 9, episodeID: 4, tag: "jackbox" },
    { id: 10, episodeID: 4, tag: "hammerwatch" },
    { id: 11, episodeID: 5, tag: "podcast" },
    { id: 12, episodeID: 6, tag: "game night" },
    { id: 13, episodeID: 6, tag: "star citizen" },
    { id: 14, episodeID: 7, tag: "podcast" },
    { id: 15, episodeID: 7, tag: "mental health" },
    { id: 16, episodeID: 8, tag: "game night" },
    { id: 17, episodeID: 8, tag: "bronzebeards tavern" },
    { id: 18, episodeID: 9, tag: "game night" },
    { id: 19, episodeID: 9, tag: "hammerwatch" },
    { id: 20, episodeID: 10, tag: "game show" },
  ]);

  console.log("Seeding People");
  await db.insert(People).values([
    {
      id: 1,
      name: "Wolf Seisenbacher",
      slug: "wolf-seisenbacher",
      orgRole: "host",
    },
    {
      id: 2,
      name: "Matorin Talfax",
      slug: "matorin-talfax",
    },
    {
      id: 3,
      name: "DevPixel",
      slug: "devpixel",
    },
    {
      id: 4,
      name: "VoidTheProtogen",
      slug: "voidtheprotogen",
    },
    {
      id: 5,
      name: "Mizuhiro Neko",
      slug: "mizuhiro-neko",
    },
    {
      id: 6,
      name: "GlitchFlux",
      slug: "glitchflux",
      orgRole: "cohost",
    },
    {
      id: 7,
      name: "NootSponge",
      slug: "nootsponge",
      orgRole: "producer",
    },
    {
      id: 8,
      name: "DefHammer",
      slug: "defhammer",
    },
    {
      id: 9,
      name: "Namogod",
      slug: "namogod",
    },
    {
      id: 10,
      name: "RaspberryKitty1",
      slug: "raspberrykitty1",
      orgRole: "cohost",
    },
    {
      id: 11,
      name: "SlyTheFloof",
      slug: "slythefloof",
    },
    {
      id: 12,
      name: "Cloud_striker",
      slug: "cloud_striker",
    },
    {
      id: 13,
      name: "Cerealbowl",
      slug: "cerealbowl",
    },
    {
      id: 14,
      name: "Beethoven",
      slug: "beethoven",
    },
  ]);

  console.log("Seeding Episode People");
  await db.insert(EpisodePeople).values([
    {
      id: 1,
      episodeID: 1,
      peopleID: 1,
      type: "crew",
      role: "host",
    },
    {
      id: 2,
      episodeID: 1,
      peopleID: 2,
      type: "crew",
      role: "cohost",
    },
    {
      id: 3,
      episodeID: 1,
      peopleID: 3,
      type: "guest",
    },
    {
      id: 4,
      episodeID: 1,
      peopleID: 4,
      type: "guest",
    },
    {
      id: 5,
      episodeID: 1,
      peopleID: 5,
      type: "guest",
    },
    {
      id: 6,
      episodeID: 2,
      peopleID: 1,
      type: "crew",
      role: "host",
    },
    {
      id: 7,
      episodeID: 2,
      peopleID: 6,
      type: "crew",
      role: "cohost",
    },
    {
      id: 8,
      episodeID: 2,
      peopleID: 2,
      type: "crew",
      role: "cohost",
    },
    {
      id: 9,
      episodeID: 2,
      peopleID: 7,
      type: "crew",
      role: "cohost",
    },
    {
      id: 10,
      episodeID: 3,
      peopleID: 1,
      type: "crew",
      role: "host",
    },
    {
      id: 11,
      episodeID: 3,
      peopleID: 6,
      type: "crew",
      role: "cohost",
    },
    {
      id: 12,
      episodeID: 3,
      peopleID: 2,
      type: "crew",
      role: "cameraSwitcher",
    },
    {
      id: 13,
      episodeID: 3,
      peopleID: 7,
      type: "crew",
      role: "producer",
    },
    {
      id: 14,
      episodeID: 3,
      peopleID: 8,
      type: "guest",
    },
    {
      id: 15,
      episodeID: 4,
      peopleID: 1,
      type: "crew",
      role: "host",
    },
    {
      id: 16,
      episodeID: 4,
      peopleID: 6,
      type: "crew",
      role: "cohost",
    },
    {
      id: 17,
      episodeID: 5,
      peopleID: 1,
      type: "crew",
      role: "host",
    },
    {
      id: 18,
      episodeID: 5,
      peopleID: 6,
      type: "crew",
      role: "cohost",
    },
    {
      id: 19,
      episodeID: 5,
      peopleID: 9,
      type: "crew",
      role: "cameraSwitcher",
    },
    {
      id: 20,
      episodeID: 5,
      peopleID: 8,
      type: "guest",
    },
    {
      id: 21,
      episodeID: 6,
      peopleID: 1,
      type: "crew",
      role: "host",
    },
    {
      id: 22,
      episodeID: 6,
      peopleID: 6,
      type: "crew",
      role: "cohost",
    },
    {
      id: 23,
      episodeID: 6,
      peopleID: 2,
      type: "crew",
      role: "cohost",
    },
    {
      id: 24,
      episodeID: 6,
      peopleID: 8,
      type: "guest",
    },
    {
      id: 25,
      episodeID: 7,
      peopleID: 1,
      type: "crew",
      role: "host",
    },
    {
      id: 26,
      episodeID: 7,
      peopleID: 6,
      type: "crew",
      role: "cohost",
    },
    {
      id: 27,
      episodeID: 7,
      peopleID: 2,
      type: "crew",
      role: "cameraSwitcher",
    },
    {
      id: 28,
      episodeID: 7,
      peopleID: 10,
      type: "crew",
      role: "cohost",
    },
    {
      id: 29,
      episodeID: 7,
      peopleID: 11,
      type: "guest",
    },
    {
      id: 30,
      episodeID: 8,
      peopleID: 1,
      type: "crew",
      role: "host",
    },
    {
      id: 31,
      episodeID: 8,
      peopleID: 6,
      type: "crew",
      role: "cohost",
    },
    {
      id: 32,
      episodeID: 8,
      peopleID: 2,
      type: "crew",
      role: "cohost",
    },
    {
      id: 33,
      episodeID: 8,
      peopleID: 10,
      type: "crew",
      role: "cohost",
    },
    {
      id: 34,
      episodeID: 8,
      peopleID: 8,
      type: "guest",
    },
    {
      id: 35,
      episodeID: 8,
      peopleID: 4,
      type: "guest",
    },
    {
      id: 36,
      episodeID: 9,
      peopleID: 1,
      type: "crew",
      role: "host",
    },
    {
      id: 37,
      episodeID: 9,
      peopleID: 6,
      type: "crew",
      role: "cohost",
    },
    {
      id: 38,
      episodeID: 9,
      peopleID: 2,
      type: "crew",
      role: "cohost",
    },
    {
      id: 39,
      episodeID: 10,
      peopleID: 1,
      type: "crew",
      role: "host",
    },
    {
      id: 40,
      episodeID: 10,
      peopleID: 6,
      type: "crew",
      role: "cohost",
    },
    {
      id: 41,
      episodeID: 10,
      peopleID: 10,
      type: "crew",
      role: "producer",
    },
    {
      id: 42,
      episodeID: 10,
      peopleID: 2,
      type: "crew",
      role: "cameraSwitcher",
    },
    {
      id: 43,
      episodeID: 10,
      peopleID: 11,
      type: "crew",
      role: "cohost",
    },
    {
      id: 44,
      episodeID: 10,
      peopleID: 8,
      type: "guest",
    },
    {
      id: 45,
      episodeID: 10,
      peopleID: 9,
      type: "guest",
    },
    {
      id: 46,
      episodeID: 10,
      peopleID: 12,
      type: "guest",
    },
    {
      id: 47,
      episodeID: 10,
      peopleID: 13,
      type: "guest",
    },
    {
      id: 48,
      episodeID: 10,
      peopleID: 14,
      type: "guest",
    },
  ]);
}
