on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/**"
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: contactsplus-web
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
