on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
        working-directory: .github/actions/episode-issues
      - id: episode-issues
        name: Run episode-issues
        uses: ./.github/actions/episode-issues
      - name: Commit changes
        if: ${{ steps.episode-issues.outputs.changed == 'true' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: "src/content"
          message: "Update episodes content (issue #${{ github.event.issue.number }})"
          new_branch: "update-episodes-${{ github.event.issue.number }}"
