on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
        working-directory: .github/actions/episode-issues
      - run: cat .github/actions/episode-issues/index.js
      - name: Run episode-issues
        uses: ./.github/actions/episode-issues
