on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run episode-issues
        uses: ./.github/actions/episode-issues
